name: perfume_gpt_mobile
packages:
  - apps/*
  - packages/*

scripts:
  analyze:
    exec: flutter analyze .
    description: Run analyze in all packages.
  test:
    exec: flutter test
    description: Run tests in all packages.
  get:
    exec: flutter pub get
    description: Run pub get in all packages.
  clean:
    exec: flutter clean
    description: Run clean in all packages.
