name: perfume_gpt_mobile
publish_to: none

environment:
  sdk: ^3.11.0

workspace:
  - apps/customer_app
  - apps/staff_app
  - packages/*

dev_dependencies:
  melos: ^7.0.0
  flutter_lints: ^6.0.0

melos:
  scripts:
    test:
      exec: flutter test
      description: Run tests in all packages.
    get:
      exec: flutter pub get
      description: Run pub get in all packages.
    clean:
      exec: flutter clean
      description: Run clean in all packages.
    generate-api:
      env:
        JAVA_OPTS: "-Dio.swagger.parser.util.RemoteUrl.trustAll=true -Dio.swagger.v3.parser.util.RemoteUrl.trustAll=true"
      steps:
        - openapi-generator-cli generate -i https://localhost:7011/openapi/v1.json -g dart-dio -o packages/perfumegpt_api_client --additional-properties=pubName=perfumegpt_api_client,serializationLibrary=json_serializable
        - melos run build-runner
      description: Regenerate the OpenAPI client and run build_runner.
    generate-ai-api:
      env:
        JAVA_OPTS: "-Dio.swagger.parser.util.RemoteUrl.trustAll=true -Dio.swagger.v3.parser.util.RemoteUrl.trustAll=true"
      steps:
        - openapi-generator-cli generate -i packages/perfumegpt_ai_api_client/v1.json -g dart-dio -o packages/perfumegpt_api_client --additional-properties=pubName=perfumegpt_api_client,serializationLibrary=json_serializable
        #- melos run build-runner
      description: Regenerate the OpenAPI client and run build_runner.
    build-runner:
      exec: |
        dart run build_runner build --delete-conflicting-outputs
      description: Run build_runner.