name: perfumegpt_common
description: Shared code for PerfumeGPT mobile apps.
version: 0.1.0
resolution: workspace

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.3.1
  riverpod_annotation: ^4.0.2
  perfumegpt_api_client: ^1.0.0
  flutter_secure_storage: ^10.0.0

  dio: any
  google_sign_in: ^7.2.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  riverpod_generator: ^4.0.3
  build_runner: 
  test: any
